apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ujgk
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0030-tenant/tkrw-pr712-0075-0030-app/devfile-sample-ujgk@sha256:9289bf5079ef66f67cdf21419bad475808ea8eae203d86e4e753900dfb0a69d2
        name: my-nodejs
        resources: {}
status: {}
